In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/raw/driver_risk.csv", sep="\t")
df.columns = df.columns.str.strip()

In [3]:
df.head()

,Weather,Road_Type,Time_of_Day,Traffic_Density,Speed_Limit,Number_of_Vehicles,Driver_Alcohol,Accident_Severity,Road_Condition,Vehicle_Type,Driver_Age,Driver_Experience,Road_Light_Condition,Accident
0,Rainy,City Road,Morning,1.0,100.0,5.0,0.0,NaN,Wet,Car,51.0,48.0,Artificial Light,0.0
1,Clear,Rural Road,Night,NaN,120.0,3.0,0.0,Moderate,Wet,Truck,49.0,43.0,Artificial Light,0.0
2,Rainy,Highway,Evening,1.0,60.0,4.0,0.0,Low,Icy,Car,54.0,52.0,Artificial Light,0.0
3,Clear,City Road,Afternoon,2.0,60.0,3.0,0.0,Low,Under Construction,Bus,34.0,31.0,Daylight,0.0
4,Rainy,Highway,Morning,1.0,195.0,11.0,0.0,Low,Dry,Car,62.0,55.0,Artificial Light,1.0

In [4]:
print("Shape:", df.shape)

Shape: (123, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Weather               117 non-null    object
 1   Road_Type             116 non-null    object
 2   Time_of_Day           121 non-null    object
 3   Traffic_Density       120 non-null    float64
 4   Speed_Limit           117 non-null    float64
 5   Number_of_Vehicles    121 non-null    float64
 6   Driver_Alcohol        115 non-null    float64
 7   Accident_Severity     118 non-null    object
 8   Road_Condition        117 non-null    object
 9   Vehicle_Type          117 non-null    object
 10  Driver_Age            116 non-null    float64
 11  Driver_Experience     113 non-null    float64
 12  Road_Light_Condition  117 non-null    object
 13  Accident              118 non-null    float64
dtypes: float64(7), object(7)
memory usage: 13.6+ KB

In [6]:
df.describe()

,Traffic_Density,Speed_Limit,Number_of_Vehicles,Driver_Alcohol,Driver_Age,Driver_Experience,Accident
count,120.000000,117.000000,121.000000,115.000000,116.000000,113.000000,118.000000
mean,0.891667,70.675214,3.421488,0.173913,44.637931,39.840708,0.305085
std,0.786395,33.351790,2.159290,0.380693,15.567746,15.588209,0.462407
min,0.000000,30.000000,1.000000,0.000000,18.000000,10.000000,0.000000
25%,0.000000,50.000000,2.000000,0.000000,32.750000,26.000000,0.000000
50%,1.000000,60.000000,3.000000,0.000000,44.500000,41.000000,0.000000
75%,2.000000,80.000000,5.000000,0.000000,59.000000,54.000000,1.000000
max,2.000000,206.000000,13.000000,1.000000,69.000000,66.000000,1.000000

In [7]:
df.isnull().sum()

Weather                  6
Road_Type                7
Time_of_Day              2
Traffic_Density          3
Speed_Limit              6
Number_of_Vehicles       2
Driver_Alcohol           8
Accident_Severity        5
Road_Condition           6
Vehicle_Type             6
Driver_Age               7
Driver_Experience       10
Road_Light_Condition     6
Accident                 5
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["Accident"].value_counts()

Accident
0.0    82
1.0    36
Name: count, dtype: int64

In [10]:
df["Accident"].value_counts(normalize=True) * 100

Accident
0.0    69.491525
1.0    30.508475
Name: proportion, dtype: float64